### ISSUE TITLE
net.sf.json.JSONException: JSONObject["secret"] not found.

### ISSUE THREAD

**Issue by tkisme** [jenkinsci/gogs-webhook-plugin#14] opened 2017-03-01 07:48 UTC
NOW USE X-Gogs-Signature

**Comment by MindTwister** [comment] 2017-03-01 20:40
I'm having the same issue

Gogs version: 0.10.1.0228
Go version 1.7.4
Jenkins version 2.48

I have attached the stack trace.

[jenkins-stacktrace.txt](https://github.com/jenkinsci/gogs-webhook-plugin/files/811977/jenkins-stacktrace.txt)

**Comment by mattddowney** [comment] 2017-03-01 20:51
Experiencing this on 0.10.1 as well, looks like the gogs update caused it, this commit specifically: https://github.com/gogits/gogs/commit/6ec859f2b0c1bade67d04f740ec4b9ac9ae0ec98

Downgrading gogs to 0.9.141 fixes the issue until the plugin can get updated.

**Comment by SMEmp** [comment] 2017-03-01 23:01
Made a pull request, was going to request a review as I haven't done Java in awhile, but it looks like it's automatically required anyway.

**Comment by sanderv32** [comment] 2017-03-02 08:08
Reviewing will be done by jenkins before I can push the merge button. Also i won't merge this pull as it only gets the header, but this value is a hexdigest which is not compared against the secret filled in Jenkins so this will definitely break the plugin!

**Comment by Unknwon** [comment] 2017-03-02 12:38
Hi...

1. Downgrade to 0.9.* can lead to unable to push because different mechanism of Git Hook.
2. This site (http://beautifytools.com/hmac-generator.php) produces same output (other sites just didn't handle line breaks correctly) from my test
3. Example:

Payload:

```
{
  "ref": "refs/heads/master",
  "before": "337fb2355f43dd74cb8d77fcd083854092086e57",
  "after": "337fb2355f43dd74cb8d77fcd083854092086e57",
  "compare_url": "",
  "commits": [
    {
      "id": "337fb2355f43dd74cb8d77fcd083854092086e57",
      "message": "Initial commit\n",
      "url": "https://try.gogs.io/unknwon/hello/commit/337fb2355f43dd74cb8d77fcd083854092086e57",
      "author": {
        "name": "无闻",
        "email": "u@gogs.io",
        "username": "unknwon"
      },
      "committer": {
        "name": "Gogs",
        "email": "gogs@fake.local",
        "username": ""
      },
      "timestamp": "0001-01-01T00:00:00Z"
    }
  ],
  "repository": {
    "id": 8427,
    "owner": {
      "id": 1,
      "login": "unknwon",
      "full_name": "Unknwon",
      "email": "u@gogs.io",
      "avatar_url": "https://secure.gravatar.com/avatar/d8b2871cdac01b57bbda23716cc03b96",
      "username": "unknwon"
    },
    "name": "hello",
    "full_name": "unknwon/hello",
    "description": "",
    "private": false,
    "fork": false,
    "html_url": "https://try.gogs.io/unknwon/hello",
    "ssh_url": "git@try.gogs.io:unknwon/hello.git",
    "clone_url": "https://try.gogs.io/unknwon/hello.git",
    "website": "",
    "stars_count": 0,
    "forks_count": 0,
    "watchers_count": 1,
    "open_issues_count": 1,
    "default_branch": "master",
    "created_at": "2017-02-21T16:14:55Z",
    "updated_at": "2017-02-21T16:14:55Z"
  },
  "pusher": {
    "id": 1,
    "login": "unknwon",
    "full_name": "Unknwon",
    "email": "u@gogs.io",
    "avatar_url": "https://secure.gravatar.com/avatar/d8b2871cdac01b57bbda23716cc03b96",
    "username": "unknwon"
  },
  "sender": {
    "id": 1,
    "login": "unknwon",
    "full_name": "Unknwon",
    "email": "u@gogs.io",
    "avatar_url": "https://secure.gravatar.com/avatar/d8b2871cdac01b57bbda23716cc03b96",
    "username": "unknwon"
  }
}
```


Secret: `111111`

Output: `9a1830da3d547ceb8bba2526a2e16f30a88974e58b6fbaac3f1d95dfec203e8d`

It is not encryption/decryption.

Not tested, but I guess http://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html#signature-v4-examples-java could do it.

Another problem is how to back-support older versions, my thoughts are:

- if header is present, use the new technic
- if not present, go with the old way

**Comment by willemvd** [comment] 2017-03-02 12:50
> Another problem is how to back-support older versions, my thoughts are:
if header is present, use the new technic
if not present, go with the old way

Think this should be the case since we otherwise would break old versions and people using this plugin with Gitea (not sure if this is ported).

We should indeed:
- If the X-Gogs-Signature header is provided -> calculate the SHA256 HMAC value with the, in Jenkins, provided secret and compare this to the value in the X-Gogs-Signature header. If valid proceed.
- If the X-Gogs-Signature header is not provided -> do like we do now and check the secret against the value in the body

**Comment by tkisme** [comment] 2017-03-02 13:43
always get 746fe31104dcebeb07e47f3e2a6d79db0d5370c87574663a45a81cc6f602c8a9

**Comment by willemvd** [comment] 2017-03-02 14:11
@tkisme what do you mean? What case? Please place your comment in context 😄

**Comment by Unknwon** [comment] 2017-03-02 18:20
@mattddowney if you haven't use any custom Git hooks, remove all `hooks` directories for all your repositories, and go admin panel to regenerate all `update` hooks.

**Comment by mattddowney** [comment] 2017-03-02 19:09
@Unknwon thanks I was able to get things going again!

Not saying this will work for everyone, but this is what I did, so do so at your own risk:

1. Rollback to 0.9.141 (hopefully you installed via docker)
2. Navigate to your gog-repositories folder
3. Run the following:
```
#!/bin/bash

for usr_dir in *
do
    # make sure $usr_dir is a directory
    if [[ -d "$usr_dir" && ! -L "$usr_dir" ]]
    then
        cd "$usr_dir"

        for repo_dir in *
        do

            # make sure $repo_dir is a directory
            if [[ -d "$repo_dir" && ! -L "$repo_dir" ]]
            then
                cd "$repo_dir"
                rm -rf hooks
                cd ..
            fi

        done

        cd ..
    fi
done
```
4. Go to admin panel and run "Rewrite all update hook of repositories (needed when custom config path is changed)"

For some reason, I was unable to restore our custom post-receive hooks by moving them over. Luckily, I do nightly backups so I have copies of all of these, and there are only a handful, so no biggie there.

**Comment by tkisme** [comment] 2017-03-03 01:03
```
find . -name custom_hooks -type d -print -delete
```
or 
```
find . -name hooks -type d -print -exec rm -rf {} \;
```

**Comment by willemvd** [comment] 2017-03-03 09:04
Is this still a request to fix here (as stated in my https://github.com/jenkinsci/gogs-webhook-plugin/issues/14#issuecomment-283645259 or is this now only a problem in Gogs?

**Comment by Unknwon** [comment] 2017-03-03 20:30
@willemvd I think you should ask Gitea devs if they have ported this feature from Gogs.

**Comment by tkisme** [comment] 2017-03-04 03:36
Tested in local.

**Comment by willemvd** [comment] 2017-03-04 10:15
@Unknown It is not yet ported to Gitea

**Comment by sanderv32** [comment] 2017-03-04 10:49
There is already a PR #16 and if this one is cleaned up and tested i can do the merge.

**Comment by tkisme** [comment] 2017-03-04 14:41
cleaned up but need more test

**Comment by sanderv32** [comment] 2017-03-06 08:43
Merged PR #16. Release of this plugin in the official repo will be this week.

**Closed** 2017-03-06 08:52 UTC
Labels: enhancement

**Comment by vpertj** [comment] 2017-03-09 06:46
Caused by: net.sf.json.JSONException: JSONObject["secret"] not found

**Comment by vpertj** [comment] 2017-03-09 06:47
© 2017 Gogs 当前版本: 0.10.8.0307

**Comment by sanderv32** [comment] 2017-03-09 08:47
@vpertj Can you please be more specific then you are now? :-)

**Comment by tkisme** [comment] 2017-03-09 09:28
@vpertj update plugin in jenkins,1.0.9 is working well
